export const ENGINE_VERSION='phase32-hit-priority-all210-v1';
export const DEFAULT_POSITION_WEIGHTS={race_score:{1:.70,2:.55,3:.40},S:{1:.10,2:.10,3:.08},H:{1:1.30,2:.15,3:.05},B:{1:.45,2:.20,3:.08},recent_score:{1:1,2:.85,3:.70},current_meet_score:{1:.90,2:.80,3:.70},condition_score:{1:.90,2:.80,3:.70},comment_score:{1:.55,2:.50,3:.45},bank_fit_score:{1:.45,2:.40,3:.35},line_position_bonus:{1:1,2:1,3:1},line_length_bonus:{1:.40,2:.50,3:.60}};
const STYLE_BASE={'逃':{1:8,2:4,3:2},'両':{1:7,2:6,3:4},'追':{1:4,2:6,3:7}};
export const CATEGORY_RULES={hit_priority:{name:'的中率優先',target_min_odds:null,target_max_odds:null},balance:{name:'穴＋バランス',target_min_odds:20,target_max_odds:60},middle:{name:'中穴',target_min_odds:60,target_max_odds:100},longshot:{name:'大穴',target_min_odds:100,target_max_odds:500},super_longshot:{name:'超大穴',target_min_odds:500,target_max_odds:null}};
const LABELS={first_position_score:'1着評価',second_position_score:'2着評価',third_position_score:'3着評価',same_line_bonus:'同ライン評価',line_order_bonus:'ライン順序評価',style_synergy_bonus:'脚質相性評価'};
const n=(v:any,d=0)=>{if(v===null||v===undefined||v==='')return d;const x=Number(v);return Number.isFinite(x)?x:d};
const rnd=(v:number,d:number)=>{const p=10**d;return Math.round((v+Number.EPSILON)*p)/p};
const avg=(v:any)=>{const x=n(v);return x<=0?0:Math.max(0,6-x)};
function recent(p:any){const r=p.recent_form||{};let s=n(r.win_rate)*.03+n(r.top2_rate)*.02+n(r.top3_rate)*.01+avg(r.avg_finish);const xs=(r.last_3_races||[]).map((x:any)=>n(x&&typeof x==='object'?x.finish:x)).filter((x:number)=>x>0);if(xs.length)s+=Math.max(0,5-xs.reduce((a:number,b:number)=>a+b,0)/xs.length);return s}
function meet(p:any){const xs=((p.current_meet||{}).results||[]).map((x:any)=>n(x&&typeof x==='object'?x.finish:x)).filter((x:number)=>x>0);return xs.length?Math.max(0,5-xs.reduce((a:number,b:number)=>a+b,0)/xs.length):0}
function comment(p:any){const f=((p.comments||{}).parsed_factors||{});return n(f.condition)+n(f.training)+n(f.equipment)+n(f.confidence)+n(f.motivation)-n(f.fatigue)}
function lp(p:any,pos:number){const x=Math.trunc(n(p.line_position));if(pos===1)return x===1?2.5:x===2?1:0;if(pos===2)return x===2?3:x===1?1.5:x===3?1:0;return x===3?3:x===2?2:x===1?.8:0}
function ll(p:any,pos:number){const x=Math.trunc(n(p.line_length));if(x<=1)return 0;if(pos===1)return Math.min(2,.5*(x-1));if(pos===2)return Math.min(2.5,.7*(x-1));return Math.min(3,.9*(x-1))}
function scorePlayer(p:any,pos:number,w:any){if(!(STYLE_BASE as any)[p.style])throw new Error(`unsupported style: ${p.style}`);const c:any={style_base:(STYLE_BASE as any)[p.style][pos],race_score:Math.max(0,(n(p.race_score,80)-80)*w.race_score[pos]),S:n(p.S)*w.S[pos],H:n(p.H)*w.H[pos],B:n(p.B)*w.B[pos],recent_form:recent(p)*w.recent_score[pos],current_meet:meet(p)*w.current_meet_score[pos],condition:n((p.condition||{}).score)*w.condition_score[pos],comments:comment(p)*w.comment_score[pos],bank_fit:n((p.bank_fit||{}).score)*w.bank_fit_score[pos],line_position:lp(p,pos)*w.line_position_bonus[pos],line_length:ll(p,pos)*w.line_length_bonus[pos]};const total=Object.values(c).reduce((a:number,b:any)=>a+Number(b),0);return{car_number:p.car_number,name:p.name,position:pos,score:rnd(total,4),contributions:Object.fromEntries(Object.entries(c).map(([k,v])=>[k,rnd(Number(v),4)]))}}
function rank(ps:any[],pos:number,w:any){const rows=ps.map(p=>scorePlayer(p,pos,w));rows.sort((a,b)=>b.score-a.score||Number(a.car_number)-Number(b.car_number));rows.forEach((r:any,i)=>r.rank=i+1);return rows}
function rankings(d:any,w:any){const ps=d.players||[];return{first:rank(ps,1,w),second:rank(ps,2,w),third:rank(ps,3,w)}}
function same(a:any,b:any,c:any){let x=0;const l1=a.line_id,l2=b.line_id,l3=c.line_id;if(l1!=null&&l1===l2)x+=3;if(l2!=null&&l2===l3)x+=1.5;if(l1!=null&&l1===l2&&l2===l3)x+=1.5;return x}
function order(a:any,b:any,c:any){let x=0,p1=a.line_position,p2=b.line_position,p3=c.line_position;if(a.line_id===b.line_id&&p1===1&&p2===2)x+=2;if(a.line_id===b.line_id&&p1===2&&p2===1)x+=2;if(a.line_id===b.line_id&&b.line_id===c.line_id&&p1===1&&p2===2&&p3===3)x+=2.5;return x}
function synergy(a:any,b:any,c:any){let x=0;if(a.style==='逃'&&['追','両'].includes(b.style))x+=1.8;if(a.style==='両'&&b.style==='追')x+=1.2;if(b.style==='追'&&['追','両'].includes(c.style))x+=.7;return x}
function perms(ns:number[]){const o:number[][]=[];for(const a of ns)for(const b of ns)if(b!==a)for(const c of ns)if(c!==a&&c!==b)o.push([a,b,c]);return o}
function norm(rows:any[],t=6){if(!rows.length)return rows;const mx=Math.max(...rows.map(r=>Number(r.score))),ws=rows.map(r=>Math.exp((Number(r.score)-mx)/t)),tot=ws.reduce((a:number,b:number)=>a+b,0);rows.forEach((r,i)=>r.estimated_probability=tot>0?ws[i]/tot:1/rows.length);return rows}
function generate(d:any,w:any=DEFAULT_POSITION_WEIGHTS){w=structuredClone(w);const rs=rankings(d,w),fm=new Map(rs.first.map((r:any)=>[Number(r.car_number),r])),sm=new Map(rs.second.map((r:any)=>[Number(r.car_number),r])),tm=new Map(rs.third.map((r:any)=>[Number(r.car_number),r])),pm=new Map((d.players||[]).map((p:any)=>[Number(p.car_number),p])),ns=[...pm.keys()].sort((a:any,b:any)=>a-b) as number[],od=((d.odds||{}).trifecta)||{},rows:any[]=[];for(const combo of perms(ns)){const[a,b,c]=combo,pa:any=pm.get(a),pb:any=pm.get(b),pc:any=pm.get(c),con:any={first_position_score:(fm.get(a) as any).score,second_position_score:(sm.get(b) as any).score,third_position_score:(tm.get(c) as any).score,same_line_bonus:same(pa,pb,pc),line_order_bonus:order(pa,pb,pc),style_synergy_bonus:synergy(pa,pb,pc)},sc=Object.values(con).reduce((x:number,y:any)=>x+Number(y),0),key=`${a}-${b}-${c}`,raw=od[key],pv=raw==null?null:Number(raw),oo=Number.isFinite(pv)?pv:null;rows.push({combo,combo_key:key,score:rnd(sc,6),contributions:Object.fromEntries(Object.entries(con).map(([k,v])=>[k,rnd(Number(v),6)])),odds:oo,expected_value_index:null,uncalibrated_odds_probability_product:null})}rows.sort((x,y)=>y.score-x.score||x.combo[0]-y.combo[0]||x.combo[1]-y.combo[1]||x.combo[2]-y.combo[2]);norm(rows);rows.forEach(r=>{if(r.odds!=null)r.uncalibrated_odds_probability_product=r.estimated_probability*r.odds});return{weights_used:w,position_rankings:rs,trifecta_scores:rows}}
const prob=(pool:any[])=>[...pool].sort((a,b)=>(b.estimated_probability||0)-(a.estimated_probability||0)||(b.score||0)-(a.score||0));
const inRange=(o:any,min:any,max:any)=>o!=null&&!(min!=null&&o<min)&&!(max!=null&&o>=max);
function take(rows:any[],used:Set<string>,limit=3){const out:any[]=[];for(const r of rows){if(used.has(r.combo_key))continue;out.push(r);used.add(r.combo_key);if(out.length>=limit)break}return out}
const status=(n:number)=>n>=3?'ready':n>0?'partial':'skipped';
function note(name:string,n:number,hasOdds:boolean){if(n>=3)return null;if(name==='的中率優先')return`全組み合わせ内の候補が${n}点です。`;if(!hasOdds)return'3連単オッズ未取得のため見送り';return`確認済みデータ内の候補が不足しているため${n}点。未確認オッズでは補完しません。`}
function select(rows:any[]){const known=rows.filter(r=>r.odds!=null),hasOdds=known.length>0,used=new Set<string>(),cats:any={},hitPool=rows,hit=take(prob(hitPool),used,3);cats.hit_priority={category_name:'的中率優先',candidate_scope:'all_combinations',status:status(hit.length),available_candidates:hitPool.length,picks:hit.map((r,i)=>({...r,rank:i+1,category:'hit_priority',category_name:'的中率優先',fallback:false,category_note:null})),category_note:note('的中率優先',hit.length,hasOdds)};for(const key of['balance','middle','longshot','super_longshot']){const rule:any=(CATEGORY_RULES as any)[key],eligible=hasOdds?known.filter(r=>!used.has(r.combo_key)&&inRange(r.odds,rule.target_min_odds,rule.target_max_odds)):[],s=hasOdds?take(prob(eligible),used,3):[];cats[key]={category_name:rule.name,candidate_scope:'confirmed_odds_only',status:status(s.length),available_candidates:eligible.length,picks:s.map((r,i)=>({...r,rank:i+1,category:key,category_name:rule.name,fallback:false,category_note:null})),category_note:note(rule.name,s.length,hasOdds)}}const total=Object.values(cats).reduce((s:number,c:any)=>s+c.picks.length,0);return{selection_policy:'hit_priority_all_combos_odds_bands_probability_uncalibrated_v2',probability_calibration_status:'uncalibrated',monetary_ev_enabled:false,odds_band_ranking:'estimated_probability_only',odds_available:hasOdds,known_odds_count:known.length,categories:cats,total_picks:total,unique_picks:used.size,complete_category_count:Object.values(cats).filter((c:any)=>c.picks.length===3).length,insufficient_categories:Object.entries(cats).filter(([,c]:any)=>c.picks.length<3).map(([k])=>k)}}
function lineText(p:any){if(p.line_id==null)return'ライン情報なし';const a=[`ライン${p.line_id}`];if(p.line_position!=null)a.push(`${p.line_position}番手`);if(p.line_length!=null)a.push(`${p.line_length}車`);return a.join('・')}
function feature(p:any,pos:number){const r:string[]=[];if(p.race_score!=null)r.push(`競走得点${p.race_score}`);if(pos===1){if(p.style==='逃')r.push('逃げ脚質を1着向きに評価');else if(p.style==='両')r.push('自在性を1着評価へ反映');if(p.B!=null&&Number(p.B)>=5)r.push(`B${p.B}で主導権候補`);if(p.H!=null&&Number(p.H)>=5)r.push(`H${p.H}で積極性あり`)}else if(pos===2){if(p.style==='追')r.push('追込脚質を2着候補として評価');else if(p.style==='両')r.push('自在性を2着評価へ反映')}else{if(p.style==='追')r.push('追込脚質を3着残り候補として評価');else if(p.style==='両')r.push('自在性を3着評価へ反映')}const cs=(p.condition||{}).score;if(cs!=null&&Number(cs)!==0)r.push(`状態評価${Number(cs)>=0?'+':''}${cs}`);const bs=(p.bank_fit||{}).score;if(bs!=null&&Number(bs)!==0)r.push(`バンク適性${Number(bs)>=0?'+':''}${bs}`);const lt=lineText(p);if(lt!=='ライン情報なし')r.push(lt);return r}
function reason(d:any,row:any){const m=new Map((d.players||[]).map((p:any)=>[Number(p.car_number),p])),[a,b,c]=row.combo,pa:any=m.get(a),pb:any=m.get(b),pc:any=m.get(c),parts=[`1着${a}番${pa.name}は${feature(pa,1).slice(0,3).join('、')}`,`2着${b}番${pb.name}は${feature(pb,2).slice(0,3).join('、')}`,`3着${c}番${pc.name}は${feature(pc,3).slice(0,3).join('、')}`],top=Object.entries(row.contributions||{}).sort((x:any,y:any)=>Math.abs(Number(y[1]))-Math.abs(Number(x[1]))).filter(([,v]:any)=>Number(v)>0).slice(0,3).map(([k,v]:any)=>`${(LABELS as any)[k]||k}+${Number(v).toFixed(2)}`);if(top.length)parts.push(`組み合わせ評価では${top.join('、')}を加点`);if(row.estimated_probability!=null)parts.push(`AI暫定推定的中率${(row.estimated_probability*100).toFixed(3)}%`);if(row.odds!=null)parts.push(`予想時オッズ${Number(row.odds).toFixed(1)}倍`);else parts.push('予想時オッズ未確認');return parts.join('。')+'。'}
function attach(d:any,s:any){for(const c of Object.values(s.categories||{}) as any[])for(const r of c.picks||[])r.reason=reason(d,r);return s}
export function buildFullPredictionWithWeights(d:any,w:any=DEFAULT_POSITION_WEIGHTS){const a=generate(d,w),s=attach(d,select(a.trifecta_scores)),cats=Object.values(s.categories) as any[],total=cats.reduce((x,c)=>x+c.picks.length,0),u=new Set(cats.flatMap(c=>c.picks.map((p:any)=>p.combo_key))),max3=cats.every(c=>c.picks.length<=3),present=cats.length===5,noFill=cats.every(c=>c.picks.every((p:any)=>p.fallback===false));if(u.size!==total)throw new Error('選択買い目に重複があります');if(!max3)throw new Error('カテゴリ上限3点を超えています');if(!present)throw new Error('5カテゴリ構成が欠落しています');return{weights_used:a.weights_used,position_rankings:a.position_rankings,trifecta_scores:a.trifecta_scores,selected_predictions:s,validation:{total_picks:total,unique_picks:u.size,five_categories_present:present,five_categories_complete:cats.every(c=>c.picks.length===3),max_three_per_category:max3,no_fallback_fill:noFill,partial_output_allowed:true}}}
